### ISSUE TITLE
Missing huggingface checkpoint

### ISSUE THREAD

**Issue by OrangeCat7777777** [ai4protein/Pro-Prime#1]
Hi!

I'm trying to run the provided notebooks. It seems that I need to download `AI4Protein/Prime_690M` but I can only find `AI4Protein/ProPrime_650M` on huggingface. Could you provide the checkpoint?

**Comment by ginnm** [comment]
I'm checking the problem; thanks for reminding us!

**Comment by ginnm** [comment]
Sorry, we forgot to make this checkpoint public. (https://huggingface.co/AI4Protein/Prime_690M, it is public available now)

**Comment by OrangeCat7777777** [comment]
Now I can successfully load the model, thanks!

However, there's another issue. 

```
total_params = sum(p.numel() for p in model.parameters())
print(total_params)
```
prints 669207175 which is roughly 670M parameters. This also matches the checkpoint size: 670M * 4Byte ~= 2.68GB. But the model name says 690M. Is this the right model?

**Comment by OrangeCat7777777** [comment]
Closing this issue as the main problem has been solved. There's another problem but I'm going to open another issue.
