### ISSUE TITLE
Parameter number mismatch of Prime_690M

### ISSUE THREAD

**Issue by OrangeCat7777777** [ai4protein/Pro-Prime#2]
I'm playing around checkpoint `AI4Protein/Prime_690M`. The following code
```
total_params = sum(p.numel() for p in model.parameters())
print(total_params)
```
prints 669207175 which is roughly 670M parameters. This also matches the checkpoint size: 670M * 4Byte ~= 2.68GB. But the model name says 690M. Is this the right model?

**Comment by ginnm** [comment]
Can you use this checkpoint to generate correct predictions of OGT?

**Comment by OrangeCat7777777** [comment]
It does generate exactly the same output as in `predict_ogt.ipynb`.

**Comment by OrangeCat7777777** [comment]
> It does generate exactly the same output as in `predict_ogt.ipynb`.

Actually not exactly, but very close. The original notebook output
```
[29.42494010925293,
 30.343338012695312,
 25.358503341674805,
 28.9854736328125,
 25.786643981933594,
 25.800437927246094,
 25.850440979003906,
 28.526737213134766,
 30.309772491455078,
 22.676509857177734,
 23.928354263305664,
 25.09626007080078,
 21.36566162109375,
 27.3638973236084]
```
My output:
```
[29.430828094482422,
 30.340259552001953,
 25.359712600708008,
 28.980998992919922,
 25.791481018066406,
 25.802265167236328,
 25.849960327148438,
 28.52544403076172,
 30.310192108154297,
 22.673341751098633,
 23.923738479614258,
 25.087505340576172,
 21.364015579223633,
 27.35865020751953]
```

**Comment by ginnm** [comment]
It looks like the contents of the notebook are out of date. We will review it. However, you can use this checkpoint temporarily。
