### ISSUE TITLE
run predict_ogt error

### ISSUE THREAD

**Issue by hml1996-fight** [ai4protein/Pro-Prime#5]
code is:
`model_path = "../Prime_690M"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = AutoModel.from_pretrained(model_path, trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model.eval()
model = model.to(device)`
`togt = []
with torch.no_grad():
    for record in tqdm(list(SeqIO.parse(sequence_file, "fasta"))):
        sequence = str(record.seq)
        tokenied_results = tokenizer(sequence, return_tensors="pt")
        input_ids = tokenied_results.input_ids.to(device)
        attention_mask = tokenied_results.attention_mask.to(device)
        logits = model(input_ids=input_ids, attention_mask=attention_mask).predicted_values
        togt.append(logits.item())`

error is:
`TypeError: scaled_dot_product_attention() got an unexpected keyword argument 'scale'`

**Comment by ginnm** [comment]
https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html

**Comment by hml1996-fight** [comment]
Thanks. Pytorch verison must > = 2.1.0 and my version is 2.0.1
