### ISSUE TITLE
Model weight acquisition request

### ISSUE THREAD

**Issue by JiaZhigang2020** [ai4protein/Pro-Prime#7]
Can model weights be open sourced? Or where can I find it?

**Comment by ginnm** [comment]
https://huggingface.co/AI4Protein/Prime_690M

**Comment by ginnm** [comment]
It has already been downloaded many times. 
![image](https://github.com/user-attachments/assets/c056f7ad-1607-4dd7-90f4-d7e0801d24fc)

**Comment by JiaZhigang2020** [comment]
Thank you so much.
